### ISSUE TITLE
Formatting Issue: Lack of Margin on Mobile Devices

### ISSUE THREAD

**Issue by fellipeutaka** [Ascend-Software/ascent-web#13]
**Problem Description:**
When viewing the project on mobile devices, the text appears to be "stuck" to the sides of the page, lacking proper margins. This results in poor visual presentation and a compromised user experience.

**Expected Behavior:**
The text should have appropriate margins on mobile devices to ensure a cleaner visual presentation and a more pleasant reading experience.

**Steps to Reproduce:**

- Access the project on a mobile device (specify the device type and browser, if relevant).
- Navigate to the page where the text is present.
- Observe how the text is "stuck" to the sides of the page.

**Screenshots:**
![image](https://github.com/Ascend-Software/ascent-web/assets/68625746/d6da2f28-c230-4578-b59c-19b504e0b6e4)

**Environment:**
Operating System: Pop!_OS 22.04 LTS
Browser: Chrome Version 118.0.5993.70 (Official Build) (64-bit)

**Comment by Kyori-kyo** [comment]
Oh my god, Japonildo!
What a good issue
We're looking into fixing it
@zKriguer please do the amazing job of doing your job and fix this

xoxo

**Comment by zKriguer** [comment]
This issue has being solved by @MatheusLukas , we are going to close this conversation for now.
